version: '2'
services:
  coinmarket-api:
    container_name: coinmarket-api
    build:
      context: docker-coinmarket-api
      dockerfile: Dockerfile
    image: coinmarket-api:latest
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - spring-cloud-network
    depends_on:
      - db
      - activemq
  converter-api:
    container_name: converter-api
    build:
      context: docker-converter-api
      dockerfile: Dockerfile
    image: converter-api:latest
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - spring-cloud-network
    depends_on:
      - db
      - activemq
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - spring-cloud-network
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge