server.port: 8081

application:
  exchange-rate-queue: "exchange.rate."
  coin-queue: "coin."

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

  datasource:
    url: jdbc:postgresql://db:5432/converter-api
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: none
  liquibase:
    enabled: true