spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/converter-api
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: none
  liquibase:
    enabled: true
